;;; pasc-2tmpl.el  Case sensitive templates for pascal mode.
;; Copyright (c) 1992 Inge Frick (I would not mind moving the copyright to FSF)
;; Address: i...@nada.kth.se
;;; This file contains templates used in pascal-mode when id-case-significant
;;; is off, so that case is significant in identifier and keyword names.

(if (null pascal-case-template-table)
    (setq pascal-case-template-table (make-abbrev-table)))

(pascal-add-templates pascal-case-template-table
 '(
   ("pg" "program ~@(input, output)~<;>\nbegin\n~<statements>\nend." t)
     ;;; For a pascal that does want input, output in the program header.
   ("pr" "procedure ~@()~<;>" t)
   ("fn" "function ~@():~<type;>" t)
   ("ex" "external;\n" t)          ; maybe change to extern
   ("fw" "forward;\n" t)
   ("lb" "label" t)
   ("cn" "const" t)
   ("tp" "type" t)
   ("vr" "var" t)
   ("ar" "array [~@] of~<type>" t)   ; maybe change to (. .)
   ("fl" "file of" t)
   ("st" "set of" t)
   ("rc" "record\n~@\nend~<;>" t)
   ("par" "packed array [~@] of~<type>" t)
   ("pst" "packed set of" t)
   ("prc" "packed record\n~@\nend~<;>" t)
   ("be" "begin ~@ end~<>" t)
   ("bg" "begin\n~@\nend~<>" t)        
   ("if" "if ~@ then~<statement>" t)
   ("ie" "if ~@ then~<statement>\nelse~<statement>" t)
   ("ei" "else if ~@ then~<statement>" t (pascal-abbrev-no-prev-semi))
   ("el" "else ~@" t (pascal-abbrev-no-prev-semi))
   ("cs" "case ~@ of\n~<cases>\nend~<>" t)
   ("ot" "otherwise~< >" t)          ; maybe change to others: or else:
   ("fr" "for ~@:=~<start> to~<end> do~<statement>" t)
   ("rp" "repeat\n~@\nuntil ~<end expression>" t)
   ("wh" "while ~@ do~<statement>" t)
   ("wt" "with ~@ do~<statement>" t)
   ("rd" "read(~@)")
   ("rdl" "readln")
   ("wr" "write(~@)")
   ("wrl" "writeln")
   ("rs" "reset(~@)")
   ("rw" "rewrite(~@)")
   ("gt" "get(~@)")
   ("pt" "put(~@)")
   ("nw" "new(~@)")
   ("ds" "dispose(~@)")
   ("pk" "pack(~@)")
   ("upk" "unpack(~@)")
   ("b" "boolean")
   ("c" "char")
   ("i" "integer")
   ("r" "real")
   ("tx" "text")
   ("ip" "input")
   ("op" "output")
   ("mi" "maxint")
   ("f" "false")
   ("t" "true")
   ("nm" "" nil (pascal-proc-name))
   ))
